### ISSUE TITLE
I always get 'action not avail to be bound' while using quest2.

### ISSUE THREAD

**Issue by qazujmko** [Omnifinity/OpenVR-Tracking-Example#12]
What do I need to do?

**Comment by peroht** [comment]
Hi, 
thanks for the question and the interest in the project. Have you checked which binding file your device tries to load? 

In the SteamVR Desktop UI, you can use the Developer > Web Console to see which binding file SteamVR is trying to load for the application in question.

Here you can find a few examples bindings files (mainly the Vive):

https://github.com/Omnifinity/OpenVR-Tracking-Example/tree/master/openvr-binding-files

This is the binding file for the Vive Controller:

https://github.com/Omnifinity/OpenVR-Tracking-Example/blob/master/openvr-binding-files/openvr_tracking_example_bindings_vive_controller.json

Most likely you are missing a) a suitable binding file for your controller and/or b) action poses and action sources with naming sceme / action path. You should be able to use one of the above referenced binding files and create a new one for your device. Remember that also must add a reference to it in the actions file

https://github.com/Omnifinity/OpenVR-Tracking-Example/blob/master/openvr-binding-files/openvr_tracking_example_actions.json

otherwise SteamVR will not find the file.

**Comment by qazujmko** [comment]
I tried to copy action.json from steamvr and fix path. But got error 3.
Anyway I have known how to get tracking data by using GetDeviceToAbsoluteTrackingPose(). Thanks
