### ISSUE TITLE
Getting Error: 3

### ISSUE THREAD

**Issue by mojodo** [Omnifinity/OpenVR-Tracking-Example#6]
Hello, thank you very much for sharing this project.
After following all steps I get an error message: Error: 3.
This error seems to correspond to `VRInputError_InvalidHandle = 3`, defined in openvr.h.
The handle you pass in line 723 of LighthouseTracking.cpp is `vr::k_ullnvalidInputValueHandle`:

`0723: inputError = vr::VRInput()->GetPoseActionDataForNextFrame(m_actionDemoHandLeft, vr::TrackingUniverseStanding, &poseData, sizeof(poseData), vr::k_ulInvalidInputValueHandle);`

To fix this problem I am tempted to pass a valid handle. However, I suspect your code is all right.
Do you have a guess what I am doing wrong?

You find the command shell output below. 

with my build
--------------------------

C:\1_Projekte\61_SteamVR\2_OpenVR_Example\OpenVR-Tracking-Example-master\Debug>"HTC Lighthouse Tracking Example.exe" --calccontrollerdeltapos 1

vive_debugger v1.5 by Omnifinity in 2020
Using openvr 1.9.16

Showing data for all devices
Successfully initialized VR Compositor
Successfully set manifest path: C:/1_Projekte/61_SteamVR/2_OpenVR_Example/OpenVR - Tracking - Example - master/Release/win32/vive_debugger_actions.json
Successfully got /actions/demo action set handle: 297
Successfully got /actions/demo/in/Hand_Left handle: 298
Successfully got /actions/demo/in/Hand_Right handle: 299
Successfully got /actions/demo/in/AnalogInput handle: 300
Successfully got /actions/demo/in/HideCubes handle: 301
Successfully got /actions/demo/in/TouchAction handle: 302
Successfully got /actions/demo/in/ClickAction handle: 303
Successfully got /user/hand/left input handle: 9
Successfully got /user/hand/right input handle: 10

Device list:
Device 0: Class: [HMD] HTC - VIVE_Pro MV [LHR-FAD0DC88] can power off: 0
Device 1: Class: [TrackingReference] Valve Corporation - Valve SR [LHB-2B0740F3] can power off: 0
Device 2: Class: [TrackingReference] Valve Corporation - Valve SR [LHB-2085BA6B] can power off: 0
End of device list

Press 'q' to quit. Starting capture of tracking data...

/actions/demo | UpdateActionState(): Ok
/actions/demo/in/AnalogInput | GetAnalogActionData() Not Ok. Error: 3
/actions/demo/in/HideCubes | GetDigitalActionData() Not Ok. Error: 3
/actions/demo/in/TouchAction | GetDigitalActionData() Not Ok. Error: 3
/actions/demo/in/ClickAction | GetDigitalActionData() Not Ok. Error: 3
/actions/demo/in/Hand_Left | GetPoseActionData() Call Not Ok. Error: 3
(lx, ly, lz) = (0.000, 0.000, 0.000) | (rx, ry, rz) = (0.000, 0.000, 0.000) | (dX, dY, dZ) = (0.000, 0.000, 0.000)

with your build 
----------------------------------------

C:\1_Projekte\61_SteamVR\2_OpenVR_Example\OpenVR-Tracking-Example-master\Binary\Release_openvr1.9.16\Release\win32>vive_debugger.exe

vive_debugger v1.5 by Omnifinity in 2020
Using openvr 1.9.16

Showing data for all devices
Successfully initialized VR Compositor
Successfully set manifest path: C:/Users/pt/Documents/Visual Studio 2013/Projects/HTC Lighthouse Tracking Example/Release/win32/vive_debugger_actions.json
Successfully got /actions/demo action set handle: 472
Successfully got /actions/demo/in/Hand_Left handle: 473
Successfully got /actions/demo/in/Hand_Right handle: 474
Successfully got /actions/demo/in/AnalogInput handle: 475
Successfully got /actions/demo/in/HideCubes handle: 476
Successfully got /user/hand/left input handle: 9
Successfully got /user/hand/right input handle: 10

Device list:
Device 0: Class: [HMD] HTC - VIVE_Pro MV [LHR-FAD0DC88] can power off: 0
Device 1: Class: [Controller] HTC - VIVE Controller Pro MV [LHR-889DEB56] can power off: 1
Device 2: Class: [TrackingReference] Valve Corporation - Valve SR [LHB-2085BA6B] can power off: 0
Device 3: Class: [TrackingReference] Valve Corporation - Valve SR [LHB-2B0740F3] can power off: 0
Device 4: Class: [Controller] HTC - VIVE Controller Pro MV [LHR-E8B85D51] can power off: 1
End of device list

Press 'q' to quit. Starting capture of tracking data...

/actions/demo | UpdateActionState(): Ok
/actions/demo/in/AnalogInput | GetAnalogActionData() Not Ok. Error: 3
/actions/demo/in/HideCubes | GetDigitalActionData() Not Ok. Error: 3
/actions/demo/in/Hand_Left | GetPoseActionData() Call Not Ok. Error: 3

**Comment by peroht** [comment]
Thanks for the comment and apologies if it does not work on your side.

This is probably related to you running the Vive Pro (and the system attempts to load manifest/bindings for the vive pro) while the example application only has manifest/binding files for the original Vive. Thus the bindings for the Vive Pro headset/controllers can not be bound properly, thus the error you are seeing. I'll see if I can prepare another binding file suitable for the Vive Pro when I get back to the office. 

Maybe you are comfortable of manually adapting the included original HTC Vive manifest file/binding/action files to your Vive Pro system before I look into it?

**Comment by peroht** [comment]
@mojodo 
I've added a binding file for vive pro. please retry.

Here are the recent changes:
https://github.com/Omnifinity/OpenVR-Tracking-Example/commit/8b92156c7a1c6b917f2ee09c1805d78968327b0b

**Comment by peroht** [comment]
Assuming this has been fixed on your side @mojodo. Closing.

**Comment by b-vo** [comment]
Hello, I'm trying to get this to work with index/knuckles. I've tried to make a new binding file but I'm not having any luck. Any tips?

**Comment by peroht** [comment]
Hi, thanks for your question. It was not tested with the Index controllers yet. Ill check asap.

Edit: Solution further down. Keeping this for future reference.

Can you share the contents of the file?

Are you able to build an executable?
What is the output from the console in your build?

**This is running the build after SteamVR has started while no hand controllers have been turned on yet:**

vive_debugger v1.6 by Omnifinity in 2020
Using openvr 1.14.15

Showing data for all devices
Successfully initialized VR Compositor
Successfully set manifest path: C:/Users/pt/Documents/Projects/HTC Lighthouse Tracking Example/Release/win32/vive_debugger_actions.json
Successfully got /actions/demo action set handle: 303
Successfully got /actions/demo/in/Hand_Left handle: 309
Successfully got /actions/demo/in/Hand_Right handle: 308
Successfully got /actions/demo/in/AnalogInput handle: 305
Successfully got /actions/demo/in/HideCubes handle: 304
Successfully got /actions/demo/in/TouchAction handle: 306
Successfully got /actions/demo/in/ClickAction handle: 307
Successfully got /user/hand/left input handle: 9
Successfully got /user/hand/right input handle: 10

Device list:
Device 0: Class: [HMD] HTC - Vive MV [LHR-EECD6030] can power off: 0
Device 1: Class: [TrackingReference] HTC - HTC V2-XD/XE [LHB-F0C07B78] can power off: 0
End of device list

Press 'q' to quit. Starting capture of tracking data...

/actions/demo | UpdateActionState(): Ok
/actions/demo/in/AnalogInput | GetAnalogActionData() Ok
/actions/demo/in/AnalogInput | action not avail to be bound
/actions/demo/in/HideCubes | GetDigitalActionData() Ok
/actions/demo/in/HideCubes | action not avail to be bound
/actions/demo/in/TouchAction | GetDigitalActionData() Ok
/actions/demo/in/TouchAction | action not avail to be bound
/actions/demo/in/ClickAction | GetDigitalActionData() Ok
/actions/demo/in/ClickAction | action not avail to be bound
/actions/demo/in/Hand_Left | GetPoseActionData() Ok
/actions/demo/in/Hand_Left | action not avail to be bound




**This is with a Vive (Original) + 2 connected Vive Wands. =>Works since there is a binding file the controller type. **

/actions/demo | UpdateActionState(): Ok
/actions/demo/in/AnalogInput | GetAnalogActionData() Ok
/actions/demo/in/AnalogInput | x: 0.000000  y:0.000000
/actions/demo/in/HideCubes | GetDigitalActionData() Ok
/actions/demo/in/HideCubes | State: 0
Action comes from left hand
/actions/demo/in/TouchAction | GetDigitalActionData() Ok
/actions/demo/in/TouchAction | State: 0
Action comes from left hand
/actions/demo/in/ClickAction | GetDigitalActionData() Ok
/actions/demo/in/ClickAction | State: 0
Action comes from left hand
/actions/demo/in/Hand_Left | GetPoseActionData() Ok
Origin: 341 Validity: 536896820 DeviceIsConnected: 1

/actions/demo/in/Hand_Left Pose
x: 1.04 y: 1.39 z: 1.26
qw: 0.75 qx: 0.13 qy: -0.65 qz: 0.03




**This is with HTC Vive + 2 Index controllers: Does not work yet since there is no binding file for the controller type. **


vive_debugger v1.6 by Omnifinity in 2020
Using openvr 1.14.15

Showing data for all devices
Successfully initialized VR Compositor
Successfully set manifest path: C:/Users/pt/Documents/Projects/HTC Lighthouse Tracking Example/Release/win32/vive_debugger_actions.json
Successfully got /actions/demo action set handle: 303
Successfully got /actions/demo/in/Hand_Left handle: 309
Successfully got /actions/demo/in/Hand_Right handle: 308
Successfully got /actions/demo/in/AnalogInput handle: 305
Successfully got /actions/demo/in/HideCubes handle: 304
Successfully got /actions/demo/in/TouchAction handle: 306
Successfully got /actions/demo/in/ClickAction handle: 307
Successfully got /user/hand/left input handle: 9
Successfully got /user/hand/right input handle: 10

Device list:
Device 0: Class: [HMD] HTC - Vive MV [LHR-EECD6030] can power off: 0
Device 1: Class: [TrackingReference] HTC - HTC V2-XD/XE [LHB-F0C07B78] can power off: 0
Device 2: Class: [Controller] Valve - Knuckles Right [LHR-B32E1F61] can power off: 1
Device 3: Class: [Controller] Valve - Knuckles Left [LHR-7887D303] can power off: 1
End of device list

Press 'q' to quit. Starting capture of tracking data...

/actions/demo | UpdateActionState(): Ok
/actions/demo/in/AnalogInput | GetAnalogActionData() Ok
/actions/demo/in/AnalogInput | action not avail to be bound
/actions/demo/in/HideCubes | GetDigitalActionData() Ok
/actions/demo/in/HideCubes | action not avail to be bound
/actions/demo/in/TouchAction | GetDigitalActionData() Ok
/actions/demo/in/TouchAction | action not avail to be bound
/actions/demo/in/ClickAction | GetDigitalActionData() Ok
/actions/demo/in/ClickAction | action not avail to be bound
/actions/demo/in/Hand_Left | GetPoseActionData() Ok
/actions/demo/in/Hand_Left | action not avail to be bound



**This is part of the debugging output I am getting from the steamvr browser log( when it does not work since no existing knuckles binding file yet).**

Fri Nov 06 2020 14:56:22.998 - Remembering SetActionManifestPath call from system.generated.vive_debugger.exe: file:///C:/Users/pt/Documents/Visual%20Studio%202013/Projects/HTC%20Lighthouse%20Tracking%20Example/Release/win32/vive_debugger_actions.json
Fri Nov 06 2020 14:56:22.999 - system.generated.vive_debugger.exe (knuckles) has no configured binding. Input will not be available
Fri Nov 06 2020 14:56:22.999 - system.generated.vive_debugger.exe (vive) has no configured binding. Input will not be available
Fri Nov 06 2020 14:56:22.999 - system.generated.vive_debugger.exe (vive_controller) attempting to load default config from

Notice that my 

vive_debugger_actions.json

does not have a knuckles configuration binding yet. Thus the input is not avail/bound properly.

If you check the header

	vr::VRActionHandle_t m_actionDemoHandLeft = vr::k_ulInvalidActionHandle;
	const char *actionDemoHandLeftPath = "/actions/demo/in/Hand_Left";

you see that that specific handle is used for extracting the pos/orientation of the controller.

Thus if you look at the source

```
	// handle for left controller pose
	inputError = vr::VRInput()->GetActionHandle(actionDemoHandLeftPath, &m_actionDemoHandLeft);
	if (inputError != vr::VRInputError_None) {
		sprintf_s(buf, sizeof(buf), "Error: Unable to get action handle: %d\n", inputError);
		printf_s(buf);
	}
	else {
		sprintf_s(buf, sizeof(buf), "Successfully got %s handle: %d\n", actionDemoHandLeftPath, m_actionDemoHandLeft);
		printf_s(buf);
	}
```

Will fail, unless you've managed to create the knuckles binding file and added it to the main manifest file of this application with reference to the correct action: 

The file vive_debugger_bindings_vive_controller.json has got this content at the top:

```
   "action_manifest_version" : 0,
   "alias_info" : {},
   "app_key" : "system.generated.vive_debugger.exe",
   "bindings" : {
      "/actions/demo" : {
         "poses" : [
            {
               "output" : "/actions/demo/in/hand_left",
               "path" : "/user/hand/left/pose/raw"
            },
            {
               "output" : "/actions/demo/in/hand_right",
               "path" : "/user/hand/right/pose/raw"
            }
         ],
    }
```

Where you can see that the /actions/demo/in/hand_left is tied to the controllers path (/user/hand/left/pose/raw). If you'd add something similar in the index bindings file it should theoretically work... :) 

I'll check out out myself as soon as I can.

**Comment by peroht** [comment]
Typical solution, _without_ editing our source code:
(ill keep the above for reference if anyone wants to know how to track down simlilar problem for new controllers later).

Copy an existing working index/knuckles file next to the other bindings file of this application. 

(In this test I just copied a random steamvr default file (for the steamtours application) from D:Program Files\Steam\steamapps\common\SteamVR\tools\steamvr_environments\game\steamtours\cfg\bindings_knuckles.json)

Edit the vive_debugger_actions.json file. 

Add e.g.

```
{
    "controller_type": "knuckles",
    "binding_url": "bindings_knuckles.json"
}

```
next to the other two controllers (vive_controller and vive_pro in this specific case).

Ensure that the "binding_url" points to the same filename as the file you copied.

Now, edit the bindings_knuckles.json file and add this at the correct place:

```
"/actions/demo" : {
"poses" : [
{
"output" : "/actions/demo/in/hand_left",
"path" : "/user/hand/left/pose/raw"
},
{
"output" : "/actions/demo/in/hand_right",
"path" : "/user/hand/right/pose/raw"
}
```

Thus, you create the link between the action defined "/actions/demo/in/hand_left" in the header file with the pose/raw of the knuckles controller.

Solution is now implemented in source code. Thanks for the report.

**Comment by peroht** [comment]
Source code updated with altered actions file and addition of a simple Index/Knuckles binding file to make project work again.

https://github.com/Omnifinity/OpenVR-Tracking-Example/commit/7570dffd28abebf5c81b9b4b69626ca584da9884

Tell me if it is working or not for you @b-vo, cheers.

**Comment by peroht** [comment]
Considering the issue resolved. Closing.
